// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	IdRequest
	UserResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IdRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *IdRequest) Reset()                    { *m = IdRequest{} }
func (m *IdRequest) String() string            { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()               {}
func (*IdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserResponse struct {
	// 用户id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// 用户名称
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// 用户性别
	Gender string `protobuf:"bytes,3,opt,name=gender" json:"gender,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func init() {
	proto.RegisterType((*IdRequest)(nil), "user.IdRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xa4, 0xb9, 0x38, 0x3d, 0x53,
	0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x94, 0xbc, 0xb8, 0x78, 0x42, 0x8b, 0x53, 0x8b, 0x82,
	0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xd1, 0xe5, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73,
	0x53, 0x25, 0x98, 0xc0, 0x22, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x5b, 0x7a, 0x6a, 0x5e, 0x4a, 0x6a,
	0x91, 0x04, 0x33, 0x58, 0x14, 0xca, 0x33, 0x32, 0xe3, 0x62, 0x01, 0x99, 0x25, 0xa4, 0xc7, 0xc5,
	0x9e, 0x9e, 0x5a, 0x02, 0x66, 0xf2, 0xeb, 0x81, 0x9d, 0x03, 0xb7, 0x5f, 0x4a, 0x08, 0x22, 0x80,
	0x6c, 0xa7, 0x13, 0x47, 0x14, 0x9b, 0x9e, 0x3e, 0x48, 0x38, 0x89, 0x0d, 0xec, 0x6e, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xaf, 0xa3, 0x36, 0xc5, 0x00, 0x00, 0x00,
}
